### ISSUE TITLE
Find .grip in parent folders

### ISSUE THREAD

**Issue by tex** [sc0ty/grip#2]
Hi,

You created wonderful tool!!!

When I generate .grip in folder A and move to folder B, grip doesn't find its data folder...

A
A/B

Can you make it so grip looks to its parent folder (and up to /) if it doesn't find .grip in current folder?

Similar like git handles its .git folder...

Thank you again for such perfect tool!

**Comment by sc0ty** [comment]
It should do it already and if it doesn't, then it's a bug.
What platform you're on?
Could you post a few lines from your .grip/files?
And how do you generate database?

**Comment by tex** [comment]
It is Windows 10. Will provide more info after weekend.

**Comment by tex** [comment]
And it also happens on Linux. Try it.
```
A/B/a.txt: test

find . -type f | gripgen
./A/B/a.txt is added into .grip/files

grip test
./A/B/a.txt:test

cd A
grip test
# nothing printed
```

**Comment by tex** [comment]
Oh, that is funny. Grip restricts results based on the current directory.

Can we have switch that will show all results from all folders?

**Comment by tex** [comment]
See #3, I added option -g to show all matches.

**Comment by sc0ty** [comment]
Yeah, that's intended behaviour. Probably I should state that more clearly in readme and --help screen.
Apologies for your extra work with debugging this.
And thanks for the switch, it could be useful.
