### ISSUE TITLE
returning pointer to local variable

### ISSUE THREAD

**Issue by tex** [sc0ty/grip#4]
This is reason why it crashes in my Windows build.

When the buffer goes out of scope.... dangling pointer...

https://github.com/sc0ty/grip/blob/e323ca6512e0c748f14e203b4098baf6402c9e87/src/general/print.cpp#L100

**Comment by sc0ty** [comment]
It is copied to std::string and returned by value, there is no dangling pointer here.
I understand that's why you closed it?

**Comment by tex** [comment]
Correct. I was too fast with clicking on new issue button. Sorry about that :)
