### ISSUE TITLE
the %zu and mingww64

### ISSUE THREAD

**Issue by tex** [sc0ty/grip#5]
The %zu problem with mingww64 is still here.

I found what is problem with the %zu on mingww64:

https://stackoverflow.com/questions/44382862/how-to-printf-a-size-t-without-warning-in-mingw-w64-gcc-7-1

Tested by adding the define #define __USE_MINGW_ANSI_STDIO 1 at the begining of print.h and it fixed the issue.

**Comment by sc0ty** [comment]
Could you check this fix?

In my Windows setup %zu works without this flag and I can see that only 32-bit build is no longer importing printf and fprintf from msvcrt. 64-bit build is still importing these two functions.
I am using mingw 6.2.0 for 64-bit builds and 4.8.1 for 32-bit.
Maybe 64-bit version of msvcrt handles %zu correctly?

**Comment by tex** [comment]
Hi, yes, this fixes the issue. Thanks!

My mingww64 is 64-bit version producing 64-bit executables, but still, without that define it doesn't know %zu.
